### ISSUE TITLE
Newtonsoft.Json.JsonReaderException: Could not convert string to integer

### ISSUE THREAD

**Issue by dgleba** [elevate/elevate.metabase.tools#13]
I am running the following command on an ubuntu 16.04 host with  Docker version 18.06.1-ce, build e68fc7a. This is metabase v30 running in docker using this code https://github.com/dgleba/386dkrmetabase .

I get the error below. Can someone help me understand if I am doing something wrong?

```
cd /srv/dkr/metabase6152
docker run --rm \
  -v $PWD:/data \
  -v $PWD/appsettings-pd8.json:/app/appsettings.json \
  elevate/elevate.metabase.tools \
  Command=export OutputFilename=/data/elevate-export-pd8.json

```

appsettings-pd8.json:
```
{
  "MetabaseApi": {
    "Url": "http://10.4.1.231:6151",
    "Username": "dgleba@stackpole.com",
    "Password": "xx"
  }
}
```

I can login successfully...
```
albe@pmdsdata8:/srv/dkr/metabase6152$ curl -X POST \
>  -H "Content-Type: application/json" \
>  -d '{"username": "dgleba@stackpole.com", "password": "x"}' \
>  http://10.4.1.231:6151/api/session
{"id":"edited..c83a-054-413-ae7e-6c3defaed7"}
```

```
Unhandled Exception: Newtonsoft.Json.JsonReaderException: Could not convert string to integer: root. Path '[0].id', line 1, position 36.
   at Newtonsoft.Json.JsonReader.ReadInt32String(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at metabase_exporter.MetabaseApi.GetAllCollections() in /sln/metabase-exporter/MetabaseApi.cs:line 176
   at metabase_exporter.MetabaseApiExport.GetMappedCollections(MetabaseApi api) in /sln/metabase-exporter/MetabaseApiExport.cs:line 88
   at metabase_exporter.MetabaseApiExport.Export(MetabaseApi api) in /sln/metabase-exporter/MetabaseApiExport.cs:line 13
   at metabase_exporter.Program.Export(MetabaseApi api, Export export) in /sln/metabase-exporter/Program.cs:line 32
   at metabase_exporter.Program.Main(String[] args) in /sln/metabase-exporter/Program.cs:line 27
   at metabase_exporter.Program.<Main>(String[] args)
```

**Comment by mausch** [comment]
Hi, I'm running Metabase 0.27 . It looks like they've made some breaking change in the API in newer versions...
tbh we're waiting on https://github.com/metabase/metabase/issues/4788 to upgrade here.

**Comment by mausch** [comment]
Sorry that's actually 0.29.3 not 0.27

**Comment by mausch** [comment]
I just upgraded my Metabase instance to 0.34.3 and exporting works fine for me :-/
I'll improve the exception messages though so we can see the offending input.

**Comment by mausch** [comment]
I just pushed a new image in case you want to try it again, hopefully it'll give us more information.
I just tested importing and exporting against 0.34.3 and worked fine for me.
