### ISSUE TITLE
Newtonsoft.Json.JsonSerializationException Error converting value 

### ISSUE THREAD

**Issue by dgleba** [elevate/elevate.metabase.tools#14]
Continuing from issue #13.

I can login in using the api. Note that I switched to an older v25 Metabase below for testing.

I am getting the error below.
Can someone tell me what it means and what I might do to address it?

```
Successful login..
albe@pmdsdata8:/srv/dkr/metabase6152$ curl -X POST \
>  -H "Content-Type: application/json" \
>  -d '{"username": "dgleba@stackpole.com", "password": "myrealpass"}' \
>  http://pmdsdata.stackpole.ca:2012/api/session
{"id":"edited x798b9c-f598-46cg-947a-4772ed7d38bx"}

```

```
cd /srv/dkr/metabase6152
docker run --rm \
  -v $PWD:/data \
  -v $PWD/appsettings-pd3.json:/app/appsettings.json \
  elevate/elevate.metabase.tools \
  Command=export OutputFilename=/data/elevate-export-pd3.json

```
```
{
  "MetabaseApi": {
    "Url": "http://pmdsdata.stackpole.ca:2012",
    "Username": "dgleba@stackpole.com",
    "Password": "x"
  }
}
```

```
albe@pmdsdata8:/srv/dkr/metabase6152$ docker run --rm   -v $PWD:/data   -v $PWD/appsettings-pd3.json:/app/appsettings.json   elevate/elevate.metabase.tools   Command=export OutputFilename=/data/elevate-export-pd3.json

Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Int32'. Path '[5].database_id', line 1, position 13569. ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at metabase_exporter.MetabaseApi.GetAllCards() in /sln/metabase-exporter/MetabaseApi.cs:line 169
   at metabase_exporter.MetabaseApiExport.GetMappedCards(MetabaseApi api, IReadOnlyDictionary`2 collectionMapping) in /sln/metabase-exporter/MetabaseApiExport.cs:line 62
   at metabase_exporter.MetabaseApiExport.Export(MetabaseApi api) in /sln/metabase-exporter/MetabaseApiExport.cs:line 14
   at metabase_exporter.Program.Export(MetabaseApi api, Export export) in /sln/metabase-exporter/Program.cs:line 32
   at metabase_exporter.Program.Main(String[] args) in /sln/metabase-exporter/Program.cs:line 27
   at metabase_exporter.Program.<Main>(String[] args)
albe@pmdsdata8:/srv/dkr/metabase6152$

```

**Comment by mausch** [comment]
It looks like 0.25 doesn't include the `database_id` in the API response for cards...
Try 0.27 which is what I use.
Unfortunately the Metabase API doesn't seem to be very stable across versions... so I expect this tool to have limited forward/backward compatibility.

**Comment by mausch** [comment]
As I mentioned in https://github.com/elevate/elevate.metabase.tools/issues/13 I have upgraded my Metabase instance and I can't repro this issue. There's better error reporting now so if you want to try again it should point us to the exact JSON that's failing to deserialize.
