### ISSUE TITLE
cannot export

### ISSUE THREAD

**Issue by mfhanif** [elevate/elevate.metabase.tools#29]
i ran this 

`docker run --rm -v /Users/hanif/Downloads/tempmetabaseexporter/appsettings.json:/app/appsettings.json elevate/elevate.metabase.tools Command=export OutputFilename=metabase-state.json` 

and encountered this error
```
Unhandled exception. System.Exception: Error initialising Metabase API for https://metabase.klikpeta.com/
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path '[11].parameters[0].default', line 1, position 11570.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at metabase_exporter.MetabaseApi.GetAllDashboards() in /sln/metabase-exporter/MetabaseApi.cs:line 214
   at metabase_exporter.Program.InitApi(MetabaseApiSettings apiSettings) in /sln/metabase-exporter/Program.cs:line 193
   --- End of inner exception stack trace ---
   at metabase_exporter.Program.InitApi(MetabaseApiSettings apiSettings) in /sln/metabase-exporter/Program.cs:line 201
   at metabase_exporter.Program.Main(String[] args) in /sln/metabase-exporter/Program.cs:line 26
   at metabase_exporter.Program.<Main>(String[] args)
```

**Comment by mausch** [comment]
Hi, what's the version of metabase?

**Comment by mfhanif** [comment]
0.43.3

**Comment by mausch** [comment]
Tested Metabase v0.43 in 35ab45b52d739631c34f24ea334d7005c3adc06a

**Comment by Koziah-Sylvester** [comment]
I seem to be the having the exact same issue. Would there be something wrong in our configuration? 

Steps taken: 
1. Downloaded repo
2. Installed .Net 8 SDK
3. Entered information into appsettings.json
4. Ran `dotnet test` and `dotnet run` Both failing. 

Running Metabase v0.47 and Metabase v0.50.

**Comment by Koziah-Sylvester** [comment]
I have decided to instead use dump to h2 command in metabase so solve my problem.

**Comment by mausch** [comment]
Fixed in https://github.com/elevate/elevate.metabase.tools/commit/a67554556e17fb18f79b7214ad6c1ca9d4a2fb03
