### ISSUE TITLE
Resource temporarily unavailable exception

### ISSUE THREAD

**Issue by JCL38-ORANGE** [elevate/elevate.metabase.tools#9]
Hello,

I am facing with the following error : 
...
Unhandled Exception: System.Exception: Error initialising Metabase API for https://www.metabase-test.fr/ ---> System.Net.Http.HttpRequestException: Resource temporarily unavailable ---> System.Net.Sockets.SocketException: Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at metabase_exporter.MetabaseSessionTokenManager.GetNewSessionToken() in /sln/metabase-exporter/MetabaseSessionTokenManager.cs:line 105
   at metabase_exporter.MetabaseSessionTokenManager.<InvalidateSessionToken>b__7_0() in /sln/metabase-exporter/MetabaseSessionTokenManager.cs:line 92
   at metabase_exporter.MetabaseSessionTokenManager.SendWithSessionToken(HttpRequestMessage request) in /sln/metabase-exporter/MetabaseSessionTokenManager.cs:line 67
   at metabase_exporter.MetabaseSessionTokenManager.Send(Func`1 request) in /sln/metabase-exporter/MetabaseSessionTokenManager.cs:line 48
   at metabase_exporter.MetabaseApi.GetAllDashboards() in /sln/metabase-exporter/MetabaseApi.cs:line 182
   at metabase_exporter.Program.InitApi(MetabaseApiSettings apiSettings) in /sln/metabase-exporter/Program.cs:line 169
   --- End of inner exception stack trace ---
   at metabase_exporter.Program.InitApi(MetabaseApiSettings apiSettings) in /sln/metabase-exporter/Program.cs:line 177
   at metabase_exporter.Program.Main(String[] args) in /sln/metabase-exporter/Program.cs:line 26
   at metabase_exporter.Program.<Main>(String[] args)
...

Thanks in advance for your help,
Regards,
Jean-Christophe

**Comment by mausch** [comment]
Hi, how are you running it? Docker?

**Comment by JCL38-ORANGE** [comment]
Hello,

Yes I run it with the following command.
sudo docker run -v `pwd`/appsettings.json:/app/appsettings.json elevate/elevate.metabase.tools metabase-exporter.exe Command=export OutputFilename=metabase-state.json
I think it is a DNS trouble. What is your opinion ?
Regards,
Jean-Christophe.

**Comment by JCL38-ORANGE** [comment]
Hello,

I solved my DNS trouble.
The export command runs completely at its end.
But the file is generated on the container.
How can I export it to my host ?
Thanks and regards,
Jean-Christophe.

**Comment by mausch** [comment]
Map a host directory to the container e.g.
```
docker run --rm \
  -v $PWD:/data \
  -v $PWD/appsettings.json:/app/appsettings.json \
  elevate/elevate.metabase.tools \
  Command=export OutputFilename=/data/metabase-state.json
```

**Comment by JCL38-ORANGE** [comment]
Thanks for your reponse.
I have just solve it with a docker cp command after the run
sudo docker run -d -it --dns <> -v `pwd`/appsettings.json:/app/appsettings.json elevate/elevate.metabase.tools metabase-export.exe Command=export OutputFilename=/app/metabase-state.json
sudo docker cp <container-id>:/app/metabase-state.json ~/TMP/metabase-state.json

I am going to test the import command. I 'll let your know the result.
Regards,
Jean-Christophe.
